trigger:
  - none

pool:
  name: 'Default'  # Use your self-hosted agent pool

steps:
  # Step : Build with Maven using the specified JDK
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test'
