trigger:
- none

pool:
  name: 'Default'

steps:
  # Step 1: Use the pre-installed Java (JDK 21) from the custom path
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'LocalDirectory'
      jdkFile: 'C:\Program Files\Java\jdk-21'
      jdkDestinationDirectory: 'C:\Program Files\Java\jdk-21'
      cleanDestinationDirectory: true

  # Step 2: Build with Maven using the JDK
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test'
