trigger:
- none

pool:
  name: 'Default'  # Use your self-hosted agent pool here

steps:
# Step 1: Set up Java 17
- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureStorage'

# Step 2: Build with Maven using the JDK 17
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
